### ISSUE TITLE
GarageSlot

### ISSUE THREAD

**Issue by Xini1** [hop1n/CarService#8]
https://github.com/hop1n/CarService/blob/main/CarService/src/main/java/org/example/model/GarageSlot.java
1) Очень бросается в глаза отсутствие пробелов между методами
2) хранение общего числа созданных объектов для присвоение id - выглядит как лишняя для этого класса обязанность. Посмотрите в сторону UUID, либо может имеет смысл вынести логику в другое место

**Comment by hop1n** [comment]
Если выносить логику в другой класс или метод, то этот класс\метод должен содержить логику итерирования id для GarageSlot и Repairer?

**Comment by Xini1** [comment]
Мне кажется, логичнее было бы иметь логику присвоения ID в классе репозитория

**Comment by Xini1** [comment]
Перефразирую: мне кажется, логично отдать обязанность присвоения ID абстракции, отвечающей за хранение.
